#ifndef __GUIMyFrame__
#define __GUIMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <iostream>
#include <wx/filedlg.h>
#include <vector>
#include <fstream>
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include <string>
#include <wx/dirdlg.h>
#include <wx/dcclient.h>
#include <wx/colordlg.h>
#include <sstream>
#include <iomanip>
#include "GUIOtherSettings.h"
#include <thread>
#include <functional>
#include <memory>

struct Frame
{
	int Time;
	sf::Texture Image;
	Frame(sf::RenderTexture &buf, int time);
	Frame(sf::Texture &img, int time);
};
/** Implementing MyFrame */
class GUIMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void ChangeSizeOfAnimation( wxMoveEvent& event );
		void Repaint_AnimationPanel( wxUpdateUIEvent& event );
		void OnSlide_AnimationSpeed( wxScrollEvent& event );
		void OnClick_RewindAnimation( wxCommandEvent& event );
		void OnClick_PlayStopAnimation( wxCommandEvent& event );
		void OnClick_GoForwardAnimation( wxCommandEvent& event );
		void OnClick_RestartAnimation( wxCommandEvent& event );
		void OnClick_OpenFileOnMenuSelection( wxCommandEvent& event );
		void OnClick_SaveAnimationToFile( wxCommandEvent& event );
		void OnClick_SetBacgroundColor(wxCommandEvent& event);
		void OnClick_ShowSavingOptions(wxCommandEvent& event);
	public:
		/** Constructor */
		GUIMyFrame( wxWindow* parent );
	//// end generated class members

		friend class GUIOtherSettings;
	private:
		sf::RenderWindow Panel;
		std::vector<Frame> Animation;
		bool ReadingOption;
		enum class States{ NoInBuffer, LoadingToBuffer, ReadyToDisplay, DuringDisplay, AfterDisplay };
		States AnimationState;
		bool ShowBg = false;
		sf::Image Background;
		bool FileNumeration;
		std::string FileName;


		void SaveAnimationToDir(const char *DirPath);
		void setButtonsActive();
		bool ReadImagesToVector(wxArrayString &paths);
		bool ReadDataToVector(const char *FileName);
		bool Read3DToVector(const char* FileName);
};

#endif // __GUIMyFrame__
