#ifndef __GUIOtherSettings__
#define __GUIOtherSettings__

/**
@file
Subclass of OtherSettings, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include "GUIMyFrame.h"
class GUIMyFrame;
/** Implementing OtherSettings */
class GUIOtherSettings : public OtherSettings
{
	protected:
		// Handlers for OtherSettings events.
		void IfCheck_ShowAnimationBackground( wxCommandEvent& event );
		void OnButton_ChoseAnimationBackground( wxCommandEvent& event );
		void setSavedFileNumeration0001( wxCommandEvent& event );
		void setSavedFileNumeration1( wxCommandEvent& event );
		void ChangeSavedFileName( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIOtherSettings(wxWindow* parent, GUIMyFrame* parentWindow);
	//// end generated class members
		GUIMyFrame *Parent;
};

#endif // __GUIOtherSettings__
